#!/usr/bin/env bash
# Only Cloudflare may talk to port 80 on this machine.
#
# Without this, anyone can hit the IP directly, skip Cloudflare and FORGE the
# CF-IPCountry / CF-Connecting-IP headers — and country routes become worthless.
# It also generates the nginx include with set_real_ip_from.
#
# Usage (root): ./cloudflare-allowlist.sh   — run it again weekly (cron).
#
# TWO SAFETY GUARDS, both born from bugs in the first version:
#
#   1. SSH is allowed BEFORE any `ufw enable`. Enabling ufw without an SSH
#      rule applies the default incoming block and locks you out of a machine
#      that is only reachable over SSH. The port comes from the running sshd
#      (`sshd -T`), not from an assumed 22.
#   2. The list is synced BY IP, never by rule number: what's missing goes in,
#      what's left over goes out. ufw ignores duplicate rules, so "note the old
#      ones, insert the new ones, delete the old ones" would delete exactly the
#      ones in effect in a week when the list didn't change — port 80 closed to
#      everyone. And every search tolerates finding nothing: with
#      `set -o pipefail`, an empty `grep` aborted the script midway.
set -euo pipefail

V4=$(curl -fsS https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS https://www.cloudflare.com/ips-v6)

# Empty list = the download failed partway. Don't touch any firewall.
if [ -z "$V4" ] || [ -z "$V6" ]; then
  echo "The Cloudflare IP list came back empty. Nothing was changed." >&2
  exit 1
fi

# nginx real_ip
REAL_IP_CONF="${NGINX_REAL_IP_CONF:-/etc/nginx/cloudflare-real-ip.conf}"
{
  echo "# generated by cloudflare-allowlist.sh at $(date -u +%FT%TZ)"
  for ip in $V4 $V6; do echo "set_real_ip_from $ip;"; done
} > "$REAL_IP_CONF"

if command -v ufw >/dev/null; then
  # 1. SSH first. Always. Even if ufw is already active: it's idempotent.
  SSH_PORTS=$(sshd -T 2>/dev/null | awk '$1 == "port" { print $2 }' || true)
  [ -n "$SSH_PORTS" ] || SSH_PORTS=22
  for port in $SSH_PORTS; do
    ufw allow "$port/tcp" comment 'ssh' >/dev/null
  done
  echo "ufw: SSH allowed on port(s): $(echo $SSH_PORTS)"

  # 2. What already exists, by IP. An empty search is normal on the first run.
  CIDR='([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]+|[0-9a-fA-F:]*:[0-9a-fA-F:]*/[0-9]+'
  CURRENT=$(ufw status | grep -i 'cloudflare' | grep -oE "$CIDR" | sort -u || true)
  DESIRED=$(printf '%s\n' $V4 $V6 | sort -u)

  # 3. Add what's missing.
  added=0
  for ip in $DESIRED; do
    if ! printf '%s\n' "$CURRENT" | grep -qxF "$ip"; then
      ufw allow from "$ip" to any port 80 proto tcp comment 'cloudflare' >/dev/null
      added=$((added + 1))
    fi
  done

  # 4. Remove what's left over — by the rule's SPECIFICATION, not its number.
  #    Also remove the open port-80 rule, if any. Only after the new ones are in.
  removed=0
  for ip in $CURRENT; do
    if ! printf '%s\n' "$DESIRED" | grep -qxF "$ip"; then
      ufw --force delete allow from "$ip" to any port 80 proto tcp >/dev/null 2>&1 || true
      removed=$((removed + 1))
    fi
  done
  ufw --force delete allow 80/tcp >/dev/null 2>&1 || true
  echo "ufw: $added range(s) added, $removed removed"

  # 5. Only now enable it, with SSH already guaranteed.
  ufw --force enable >/dev/null
  echo "ufw: port 80 open only to $(echo "$V4 $V6" | wc -w | tr -d ' ') Cloudflare ranges"
else
  echo "ufw not found: apply the ranges in your firewall (nftables/iptables/cloud)." >&2
fi

nginx -t && systemctl reload nginx
