<?php
/**
 * The country of each IANA time zone a browser may report (the checkpoint's
 * tz_mismatch): lowercased zone name → ISO 3166 alpha-2.
 *
 * Generated from pages.tz_zone_country — tzdata's zone.tab (one country per
 * zone, the zone's main one: Europe/Zurich is CH, Europe/Vaduz is LI) plus the
 * `backward` aliases real browsers still resolve to (america/indianapolis,
 * asia/calcutta, us/eastern…), which PHP's own tzdata can't place
 * (getLocation gives "??"). Nine aliases of merged zones are corrected here
 * by hand (america/virgin is VI, not PR; america/coral_harbour is CA, not PA;
 * africa/asmera ER; africa/timbuktu ML; antarctica/south_pole AQ;
 * atlantic/jan_mayen NO; pacific/ponape, truk and yap FM).
 *
 * UTC, Etc/* and the POSIX-style names (EST5EDT…) have no country. A name
 * that isn't here falls back to PHP's tzdata (a zone newer than this list).
 */

declare(strict_types=1);

defined('DAYONE_ENTRY') || (http_response_code(404) && exit);

/** The zone's country, or null (no country, or a name nobody knows). */
function tz_country(string $zone): ?string
{
    static $map = [
        'africa/abidjan' => 'CI', 'africa/accra' => 'GH', 'africa/addis_ababa' => 'ET', 'africa/algiers' => 'DZ',
        'africa/asmara' => 'ER', 'africa/asmera' => 'ER', 'africa/bamako' => 'ML', 'africa/bangui' => 'CF',
        'africa/banjul' => 'GM', 'africa/bissau' => 'GW', 'africa/blantyre' => 'MW', 'africa/brazzaville' => 'CG',
        'africa/bujumbura' => 'BI', 'africa/cairo' => 'EG', 'africa/casablanca' => 'MA', 'africa/ceuta' => 'ES',
        'africa/conakry' => 'GN', 'africa/dakar' => 'SN', 'africa/dar_es_salaam' => 'TZ', 'africa/djibouti' => 'DJ',
        'africa/douala' => 'CM', 'africa/el_aaiun' => 'EH', 'africa/freetown' => 'SL', 'africa/gaborone' => 'BW',
        'africa/harare' => 'ZW', 'africa/johannesburg' => 'ZA', 'africa/juba' => 'SS', 'africa/kampala' => 'UG',
        'africa/khartoum' => 'SD', 'africa/kigali' => 'RW', 'africa/kinshasa' => 'CD', 'africa/lagos' => 'NG',
        'africa/libreville' => 'GA', 'africa/lome' => 'TG', 'africa/luanda' => 'AO', 'africa/lubumbashi' => 'CD',
        'africa/lusaka' => 'ZM', 'africa/malabo' => 'GQ', 'africa/maputo' => 'MZ', 'africa/maseru' => 'LS',
        'africa/mbabane' => 'SZ', 'africa/mogadishu' => 'SO', 'africa/monrovia' => 'LR', 'africa/nairobi' => 'KE',
        'africa/ndjamena' => 'TD', 'africa/niamey' => 'NE', 'africa/nouakchott' => 'MR',
        'africa/ouagadougou' => 'BF', 'africa/porto-novo' => 'BJ', 'africa/sao_tome' => 'ST',
        'africa/timbuktu' => 'ML', 'africa/tripoli' => 'LY', 'africa/tunis' => 'TN', 'africa/windhoek' => 'NA',
        'america/adak' => 'US', 'america/anchorage' => 'US', 'america/anguilla' => 'AI', 'america/antigua' => 'AG',
        'america/araguaina' => 'BR', 'america/argentina/buenos_aires' => 'AR', 'america/argentina/catamarca' => 'AR',
        'america/argentina/comodrivadavia' => 'AR', 'america/argentina/cordoba' => 'AR',
        'america/argentina/jujuy' => 'AR', 'america/argentina/la_rioja' => 'AR', 'america/argentina/mendoza' => 'AR',
        'america/argentina/rio_gallegos' => 'AR', 'america/argentina/salta' => 'AR',
        'america/argentina/san_juan' => 'AR', 'america/argentina/san_luis' => 'AR',
        'america/argentina/tucuman' => 'AR', 'america/argentina/ushuaia' => 'AR', 'america/aruba' => 'AW',
        'america/asuncion' => 'PY', 'america/atikokan' => 'CA', 'america/atka' => 'US', 'america/bahia' => 'BR',
        'america/bahia_banderas' => 'MX', 'america/barbados' => 'BB', 'america/belem' => 'BR',
        'america/belize' => 'BZ', 'america/blanc-sablon' => 'CA', 'america/boa_vista' => 'BR',
        'america/bogota' => 'CO', 'america/boise' => 'US', 'america/buenos_aires' => 'AR',
        'america/cambridge_bay' => 'CA', 'america/campo_grande' => 'BR', 'america/cancun' => 'MX',
        'america/caracas' => 'VE', 'america/catamarca' => 'AR', 'america/cayenne' => 'GF', 'america/cayman' => 'KY',
        'america/chicago' => 'US', 'america/chihuahua' => 'MX', 'america/ciudad_juarez' => 'MX',
        'america/coral_harbour' => 'CA', 'america/cordoba' => 'AR', 'america/costa_rica' => 'CR',
        'america/coyhaique' => 'CL', 'america/creston' => 'CA', 'america/cuiaba' => 'BR', 'america/curacao' => 'CW',
        'america/danmarkshavn' => 'GL', 'america/dawson' => 'CA', 'america/dawson_creek' => 'CA',
        'america/denver' => 'US', 'america/detroit' => 'US', 'america/dominica' => 'DM', 'america/edmonton' => 'CA',
        'america/eirunepe' => 'BR', 'america/el_salvador' => 'SV', 'america/ensenada' => 'MX',
        'america/fort_nelson' => 'CA', 'america/fort_wayne' => 'US', 'america/fortaleza' => 'BR',
        'america/glace_bay' => 'CA', 'america/godthab' => 'GL', 'america/goose_bay' => 'CA',
        'america/grand_turk' => 'TC', 'america/grenada' => 'GD', 'america/guadeloupe' => 'GP',
        'america/guatemala' => 'GT', 'america/guayaquil' => 'EC', 'america/guyana' => 'GY',
        'america/halifax' => 'CA', 'america/havana' => 'CU', 'america/hermosillo' => 'MX',
        'america/indiana/indianapolis' => 'US', 'america/indiana/knox' => 'US', 'america/indiana/marengo' => 'US',
        'america/indiana/petersburg' => 'US', 'america/indiana/tell_city' => 'US', 'america/indiana/vevay' => 'US',
        'america/indiana/vincennes' => 'US', 'america/indiana/winamac' => 'US', 'america/indianapolis' => 'US',
        'america/inuvik' => 'CA', 'america/iqaluit' => 'CA', 'america/jamaica' => 'JM', 'america/jujuy' => 'AR',
        'america/juneau' => 'US', 'america/kentucky/louisville' => 'US', 'america/kentucky/monticello' => 'US',
        'america/knox_in' => 'US', 'america/kralendijk' => 'BQ', 'america/la_paz' => 'BO', 'america/lima' => 'PE',
        'america/los_angeles' => 'US', 'america/louisville' => 'US', 'america/lower_princes' => 'SX',
        'america/maceio' => 'BR', 'america/managua' => 'NI', 'america/manaus' => 'BR', 'america/marigot' => 'MF',
        'america/martinique' => 'MQ', 'america/matamoros' => 'MX', 'america/mazatlan' => 'MX',
        'america/mendoza' => 'AR', 'america/menominee' => 'US', 'america/merida' => 'MX',
        'america/metlakatla' => 'US', 'america/mexico_city' => 'MX', 'america/miquelon' => 'PM',
        'america/moncton' => 'CA', 'america/monterrey' => 'MX', 'america/montevideo' => 'UY',
        'america/montreal' => 'CA', 'america/montserrat' => 'MS', 'america/nassau' => 'BS',
        'america/new_york' => 'US', 'america/nipigon' => 'CA', 'america/nome' => 'US', 'america/noronha' => 'BR',
        'america/north_dakota/beulah' => 'US', 'america/north_dakota/center' => 'US',
        'america/north_dakota/new_salem' => 'US', 'america/nuuk' => 'GL', 'america/ojinaga' => 'MX',
        'america/panama' => 'PA', 'america/pangnirtung' => 'CA', 'america/paramaribo' => 'SR',
        'america/phoenix' => 'US', 'america/port-au-prince' => 'HT', 'america/port_of_spain' => 'TT',
        'america/porto_acre' => 'BR', 'america/porto_velho' => 'BR', 'america/puerto_rico' => 'PR',
        'america/punta_arenas' => 'CL', 'america/rainy_river' => 'CA', 'america/rankin_inlet' => 'CA',
        'america/recife' => 'BR', 'america/regina' => 'CA', 'america/resolute' => 'CA', 'america/rio_branco' => 'BR',
        'america/rosario' => 'AR', 'america/santa_isabel' => 'MX', 'america/santarem' => 'BR',
        'america/santiago' => 'CL', 'america/santo_domingo' => 'DO', 'america/sao_paulo' => 'BR',
        'america/scoresbysund' => 'GL', 'america/shiprock' => 'US', 'america/sitka' => 'US',
        'america/st_barthelemy' => 'BL', 'america/st_johns' => 'CA', 'america/st_kitts' => 'KN',
        'america/st_lucia' => 'LC', 'america/st_thomas' => 'VI', 'america/st_vincent' => 'VC',
        'america/swift_current' => 'CA', 'america/tegucigalpa' => 'HN', 'america/thule' => 'GL',
        'america/thunder_bay' => 'CA', 'america/tijuana' => 'MX', 'america/toronto' => 'CA',
        'america/tortola' => 'VG', 'america/vancouver' => 'CA', 'america/virgin' => 'VI',
        'america/whitehorse' => 'CA', 'america/winnipeg' => 'CA', 'america/yakutat' => 'US',
        'america/yellowknife' => 'CA',
        'antarctica/casey' => 'AQ', 'antarctica/davis' => 'AQ', 'antarctica/dumontdurville' => 'AQ',
        'antarctica/macquarie' => 'AU', 'antarctica/mawson' => 'AQ', 'antarctica/mcmurdo' => 'AQ',
        'antarctica/palmer' => 'AQ', 'antarctica/rothera' => 'AQ', 'antarctica/south_pole' => 'AQ',
        'antarctica/syowa' => 'AQ', 'antarctica/troll' => 'AQ', 'antarctica/vostok' => 'AQ',
        'arctic/longyearbyen' => 'SJ',
        'asia/aden' => 'YE', 'asia/almaty' => 'KZ', 'asia/amman' => 'JO', 'asia/anadyr' => 'RU',
        'asia/aqtau' => 'KZ', 'asia/aqtobe' => 'KZ', 'asia/ashgabat' => 'TM', 'asia/ashkhabad' => 'TM',
        'asia/atyrau' => 'KZ', 'asia/baghdad' => 'IQ', 'asia/bahrain' => 'BH', 'asia/baku' => 'AZ',
        'asia/bangkok' => 'TH', 'asia/barnaul' => 'RU', 'asia/beirut' => 'LB', 'asia/bishkek' => 'KG',
        'asia/brunei' => 'BN', 'asia/calcutta' => 'IN', 'asia/chita' => 'RU', 'asia/choibalsan' => 'MN',
        'asia/chongqing' => 'CN', 'asia/chungking' => 'CN', 'asia/colombo' => 'LK', 'asia/dacca' => 'BD',
        'asia/damascus' => 'SY', 'asia/dhaka' => 'BD', 'asia/dili' => 'TL', 'asia/dubai' => 'AE',
        'asia/dushanbe' => 'TJ', 'asia/famagusta' => 'CY', 'asia/gaza' => 'PS', 'asia/harbin' => 'CN',
        'asia/hebron' => 'PS', 'asia/ho_chi_minh' => 'VN', 'asia/hong_kong' => 'HK', 'asia/hovd' => 'MN',
        'asia/irkutsk' => 'RU', 'asia/istanbul' => 'TR', 'asia/jakarta' => 'ID', 'asia/jayapura' => 'ID',
        'asia/jerusalem' => 'IL', 'asia/kabul' => 'AF', 'asia/kamchatka' => 'RU', 'asia/karachi' => 'PK',
        'asia/kashgar' => 'CN', 'asia/kathmandu' => 'NP', 'asia/katmandu' => 'NP', 'asia/khandyga' => 'RU',
        'asia/kolkata' => 'IN', 'asia/krasnoyarsk' => 'RU', 'asia/kuala_lumpur' => 'MY', 'asia/kuching' => 'MY',
        'asia/kuwait' => 'KW', 'asia/macao' => 'MO', 'asia/macau' => 'MO', 'asia/magadan' => 'RU',
        'asia/makassar' => 'ID', 'asia/manila' => 'PH', 'asia/muscat' => 'OM', 'asia/nicosia' => 'CY',
        'asia/novokuznetsk' => 'RU', 'asia/novosibirsk' => 'RU', 'asia/omsk' => 'RU', 'asia/oral' => 'KZ',
        'asia/phnom_penh' => 'KH', 'asia/pontianak' => 'ID', 'asia/pyongyang' => 'KP', 'asia/qatar' => 'QA',
        'asia/qostanay' => 'KZ', 'asia/qyzylorda' => 'KZ', 'asia/rangoon' => 'MM', 'asia/riyadh' => 'SA',
        'asia/saigon' => 'VN', 'asia/sakhalin' => 'RU', 'asia/samarkand' => 'UZ', 'asia/seoul' => 'KR',
        'asia/shanghai' => 'CN', 'asia/singapore' => 'SG', 'asia/srednekolymsk' => 'RU', 'asia/taipei' => 'TW',
        'asia/tashkent' => 'UZ', 'asia/tbilisi' => 'GE', 'asia/tehran' => 'IR', 'asia/tel_aviv' => 'IL',
        'asia/thimbu' => 'BT', 'asia/thimphu' => 'BT', 'asia/tokyo' => 'JP', 'asia/tomsk' => 'RU',
        'asia/ujung_pandang' => 'ID', 'asia/ulaanbaatar' => 'MN', 'asia/ulan_bator' => 'MN', 'asia/urumqi' => 'CN',
        'asia/ust-nera' => 'RU', 'asia/vientiane' => 'LA', 'asia/vladivostok' => 'RU', 'asia/yakutsk' => 'RU',
        'asia/yangon' => 'MM', 'asia/yekaterinburg' => 'RU', 'asia/yerevan' => 'AM',
        'atlantic/azores' => 'PT', 'atlantic/bermuda' => 'BM', 'atlantic/canary' => 'ES',
        'atlantic/cape_verde' => 'CV', 'atlantic/faeroe' => 'FO', 'atlantic/faroe' => 'FO',
        'atlantic/jan_mayen' => 'NO', 'atlantic/madeira' => 'PT', 'atlantic/reykjavik' => 'IS',
        'atlantic/south_georgia' => 'GS', 'atlantic/st_helena' => 'SH', 'atlantic/stanley' => 'FK',
        'australia/act' => 'AU', 'australia/adelaide' => 'AU', 'australia/brisbane' => 'AU',
        'australia/broken_hill' => 'AU', 'australia/canberra' => 'AU', 'australia/currie' => 'AU',
        'australia/darwin' => 'AU', 'australia/eucla' => 'AU', 'australia/hobart' => 'AU', 'australia/lhi' => 'AU',
        'australia/lindeman' => 'AU', 'australia/lord_howe' => 'AU', 'australia/melbourne' => 'AU',
        'australia/north' => 'AU', 'australia/nsw' => 'AU', 'australia/perth' => 'AU',
        'australia/queensland' => 'AU', 'australia/south' => 'AU', 'australia/sydney' => 'AU',
        'australia/tasmania' => 'AU', 'australia/victoria' => 'AU', 'australia/west' => 'AU',
        'australia/yancowinna' => 'AU',
        'brazil/acre' => 'BR', 'brazil/denoronha' => 'BR', 'brazil/east' => 'BR', 'brazil/west' => 'BR',
        'canada/atlantic' => 'CA', 'canada/central' => 'CA', 'canada/eastern' => 'CA', 'canada/mountain' => 'CA',
        'canada/newfoundland' => 'CA', 'canada/pacific' => 'CA', 'canada/saskatchewan' => 'CA',
        'canada/yukon' => 'CA',
        'cet' => 'BE',
        'chile/continental' => 'CL', 'chile/easterisland' => 'CL',
        'cuba' => 'CU',
        'eet' => 'GR',
        'egypt' => 'EG',
        'eire' => 'IE',
        'est' => 'PA',
        'europe/amsterdam' => 'NL', 'europe/andorra' => 'AD', 'europe/astrakhan' => 'RU', 'europe/athens' => 'GR',
        'europe/belfast' => 'GB', 'europe/belgrade' => 'RS', 'europe/berlin' => 'DE', 'europe/bratislava' => 'SK',
        'europe/brussels' => 'BE', 'europe/bucharest' => 'RO', 'europe/budapest' => 'HU', 'europe/busingen' => 'DE',
        'europe/chisinau' => 'MD', 'europe/copenhagen' => 'DK', 'europe/dublin' => 'IE', 'europe/gibraltar' => 'GI',
        'europe/guernsey' => 'GG', 'europe/helsinki' => 'FI', 'europe/isle_of_man' => 'IM',
        'europe/istanbul' => 'TR', 'europe/jersey' => 'JE', 'europe/kaliningrad' => 'RU', 'europe/kiev' => 'UA',
        'europe/kirov' => 'RU', 'europe/kyiv' => 'UA', 'europe/lisbon' => 'PT', 'europe/ljubljana' => 'SI',
        'europe/london' => 'GB', 'europe/luxembourg' => 'LU', 'europe/madrid' => 'ES', 'europe/malta' => 'MT',
        'europe/mariehamn' => 'AX', 'europe/minsk' => 'BY', 'europe/monaco' => 'MC', 'europe/moscow' => 'RU',
        'europe/nicosia' => 'CY', 'europe/oslo' => 'NO', 'europe/paris' => 'FR', 'europe/podgorica' => 'ME',
        'europe/prague' => 'CZ', 'europe/riga' => 'LV', 'europe/rome' => 'IT', 'europe/samara' => 'RU',
        'europe/san_marino' => 'SM', 'europe/sarajevo' => 'BA', 'europe/saratov' => 'RU',
        'europe/simferopol' => 'UA', 'europe/skopje' => 'MK', 'europe/sofia' => 'BG', 'europe/stockholm' => 'SE',
        'europe/tallinn' => 'EE', 'europe/tirane' => 'AL', 'europe/tiraspol' => 'MD', 'europe/ulyanovsk' => 'RU',
        'europe/uzhgorod' => 'UA', 'europe/vaduz' => 'LI', 'europe/vatican' => 'VA', 'europe/vienna' => 'AT',
        'europe/vilnius' => 'LT', 'europe/volgograd' => 'RU', 'europe/warsaw' => 'PL', 'europe/zagreb' => 'HR',
        'europe/zaporozhye' => 'UA', 'europe/zurich' => 'CH',
        'gb' => 'GB',
        'gb-eire' => 'GB',
        'hongkong' => 'HK',
        'hst' => 'US',
        'iceland' => 'CI',
        'indian/antananarivo' => 'MG', 'indian/chagos' => 'IO', 'indian/christmas' => 'CX', 'indian/cocos' => 'CC',
        'indian/comoro' => 'KM', 'indian/kerguelen' => 'TF', 'indian/mahe' => 'SC', 'indian/maldives' => 'MV',
        'indian/mauritius' => 'MU', 'indian/mayotte' => 'YT', 'indian/reunion' => 'RE',
        'iran' => 'IR',
        'israel' => 'IL',
        'jamaica' => 'JM',
        'japan' => 'JP',
        'kwajalein' => 'MH',
        'libya' => 'LY',
        'met' => 'BE',
        'mexico/bajanorte' => 'MX', 'mexico/bajasur' => 'MX', 'mexico/general' => 'MX',
        'mst' => 'US',
        'navajo' => 'US',
        'nz' => 'NZ',
        'nz-chat' => 'NZ',
        'pacific/apia' => 'WS', 'pacific/auckland' => 'NZ', 'pacific/bougainville' => 'PG',
        'pacific/chatham' => 'NZ', 'pacific/chuuk' => 'FM', 'pacific/easter' => 'CL', 'pacific/efate' => 'VU',
        'pacific/enderbury' => 'KI', 'pacific/fakaofo' => 'TK', 'pacific/fiji' => 'FJ', 'pacific/funafuti' => 'TV',
        'pacific/galapagos' => 'EC', 'pacific/gambier' => 'PF', 'pacific/guadalcanal' => 'SB',
        'pacific/guam' => 'GU', 'pacific/honolulu' => 'US', 'pacific/johnston' => 'US', 'pacific/kanton' => 'KI',
        'pacific/kiritimati' => 'KI', 'pacific/kosrae' => 'FM', 'pacific/kwajalein' => 'MH',
        'pacific/majuro' => 'MH', 'pacific/marquesas' => 'PF', 'pacific/midway' => 'UM', 'pacific/nauru' => 'NR',
        'pacific/niue' => 'NU', 'pacific/norfolk' => 'NF', 'pacific/noumea' => 'NC', 'pacific/pago_pago' => 'AS',
        'pacific/palau' => 'PW', 'pacific/pitcairn' => 'PN', 'pacific/pohnpei' => 'FM', 'pacific/ponape' => 'FM',
        'pacific/port_moresby' => 'PG', 'pacific/rarotonga' => 'CK', 'pacific/saipan' => 'MP',
        'pacific/samoa' => 'AS', 'pacific/tahiti' => 'PF', 'pacific/tarawa' => 'KI', 'pacific/tongatapu' => 'TO',
        'pacific/truk' => 'FM', 'pacific/wake' => 'UM', 'pacific/wallis' => 'WF', 'pacific/yap' => 'FM',
        'poland' => 'PL',
        'portugal' => 'PT',
        'prc' => 'CN',
        'roc' => 'TW',
        'rok' => 'KR',
        'singapore' => 'SG',
        'turkey' => 'TR',
        'us/alaska' => 'US', 'us/aleutian' => 'US', 'us/arizona' => 'US', 'us/central' => 'US',
        'us/east-indiana' => 'US', 'us/eastern' => 'US', 'us/hawaii' => 'US', 'us/indiana-starke' => 'US',
        'us/michigan' => 'US', 'us/mountain' => 'US', 'us/pacific' => 'US', 'us/samoa' => 'AS',
        'w-su' => 'RU',
        'wet' => 'PT',
    ];
    $z = strtolower(trim($zone));
    if ($z === '') {
        return null;
    }
    if (isset($map[$z])) {
        return $map[$z];
    }
    try {
        $loc = (new DateTimeZone($z))->getLocation();
    } catch (Throwable) {
        return null;
    }
    $cc = is_array($loc) ? (string) ($loc['country_code'] ?? '') : '';
    return preg_match('/^[A-Z]{2}$/', $cc) === 1 ? $cc : null;
}
